/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IConditionChecker,
  IConditionCheckerInterface,
} from "../../../../contracts/flattened/EpochRegistry.sol/IConditionChecker";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "userInput",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "onChainCondition",
        type: "bytes",
      },
    ],
    name: "checkCondition",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IConditionChecker__factory {
  static readonly abi = _abi;
  static createInterface(): IConditionCheckerInterface {
    return new utils.Interface(_abi) as IConditionCheckerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConditionChecker {
    return new Contract(address, _abi, signerOrProvider) as IConditionChecker;
  }
}
