/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ByteManipulationLibraryInterface extends utils.Interface {
  functions: {
    "getDynamicData(bytes,uint256)": FunctionFragment;
    "getDynamicSizeDynamicArrayData(bytes,uint256)": FunctionFragment;
    "getFixedData(bytes,uint256)": FunctionFragment;
    "getFixedSizeDynamicArrayData(bytes,uint256)": FunctionFragment;
    "getStaticArrayData(bytes,uint256)": FunctionFragment;
    "overwriteStaticDataWithSignature(bytes,bytes32,uint32)": FunctionFragment;
    "overwriteStaticDataWithoutSignature(bytes,bytes32,uint32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getDynamicData"
      | "getDynamicSizeDynamicArrayData"
      | "getFixedData"
      | "getFixedSizeDynamicArrayData"
      | "getStaticArrayData"
      | "overwriteStaticDataWithSignature"
      | "overwriteStaticDataWithoutSignature"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getDynamicData",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDynamicSizeDynamicArrayData",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFixedData",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFixedSizeDynamicArrayData",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStaticArrayData",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "overwriteStaticDataWithSignature",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "overwriteStaticDataWithoutSignature",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getDynamicData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDynamicSizeDynamicArrayData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFixedData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFixedSizeDynamicArrayData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStaticArrayData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "overwriteStaticDataWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "overwriteStaticDataWithoutSignature",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ByteManipulationLibrary extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ByteManipulationLibraryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getDynamicData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getDynamicSizeDynamicArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getFixedData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getFixedSizeDynamicArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getStaticArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    overwriteStaticDataWithSignature(
      data: PromiseOrValue<BytesLike>,
      dataToOverwrite: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    overwriteStaticDataWithoutSignature(
      data: PromiseOrValue<BytesLike>,
      dataToOverwrite: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  getDynamicData(
    data: PromiseOrValue<BytesLike>,
    position: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getDynamicSizeDynamicArrayData(
    data: PromiseOrValue<BytesLike>,
    position: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getFixedData(
    data: PromiseOrValue<BytesLike>,
    position: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getFixedSizeDynamicArrayData(
    data: PromiseOrValue<BytesLike>,
    position: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getStaticArrayData(
    data: PromiseOrValue<BytesLike>,
    position: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  overwriteStaticDataWithSignature(
    data: PromiseOrValue<BytesLike>,
    dataToOverwrite: PromiseOrValue<BytesLike>,
    position: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  overwriteStaticDataWithoutSignature(
    data: PromiseOrValue<BytesLike>,
    dataToOverwrite: PromiseOrValue<BytesLike>,
    position: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getDynamicData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getDynamicSizeDynamicArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getFixedData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getFixedSizeDynamicArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getStaticArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    overwriteStaticDataWithSignature(
      data: PromiseOrValue<BytesLike>,
      dataToOverwrite: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    overwriteStaticDataWithoutSignature(
      data: PromiseOrValue<BytesLike>,
      dataToOverwrite: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getDynamicData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDynamicSizeDynamicArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFixedData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFixedSizeDynamicArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStaticArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    overwriteStaticDataWithSignature(
      data: PromiseOrValue<BytesLike>,
      dataToOverwrite: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    overwriteStaticDataWithoutSignature(
      data: PromiseOrValue<BytesLike>,
      dataToOverwrite: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getDynamicData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDynamicSizeDynamicArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFixedData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFixedSizeDynamicArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStaticArrayData(
      data: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    overwriteStaticDataWithSignature(
      data: PromiseOrValue<BytesLike>,
      dataToOverwrite: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    overwriteStaticDataWithoutSignature(
      data: PromiseOrValue<BytesLike>,
      dataToOverwrite: PromiseOrValue<BytesLike>,
      position: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
