/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as epochRegistrySol from "./EpochRegistry.sol";
export type { epochRegistrySol };
import type * as epochWalletSol from "./EpochWallet.sol";
export type { epochWalletSol };
import type * as epochWalletFactorySol from "./EpochWalletFactory.sol";
export type { epochWalletFactorySol };
