/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as epochRegistrySol from "./EpochRegistry.sol";
export * as epochWalletSol from "./EpochWallet.sol";
export * as epochWalletFactorySol from "./EpochWalletFactory.sol";
